In [1]:
#to concatenate 2D arrays column wise and row wise

In [7]:
import numpy as np

In [13]:
data1 = np.arange(1,10).reshape(3,3)
data2 = np.arange(10,19).reshape(3,3)
print(np.concatenate((data1,data2),axis=1))
print(np.concatenate((data1,data2),axis=0))


[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
