In [1]:
#To store array as contigoues flattened array

In [2]:
import numpy as np

In [7]:
data = np.array([[10,20,30],[40,50,60]])
print(data)
print(data.ndim)

[[10 20 30]
 [40 50 60]]
2


In [10]:
flatarray = np.ravel(data)
print(flatarray)
print(flatarray.ndim)

[10 20 30 40 50 60]
1
