In [3]:
#To convert list and tuple to array


In [4]:
import numpy as np

In [7]:
listdata = [1,2,3,4,5,6]
tupledata = ([8, 4, 6], [1, 2, 3])
print(type(listdata))
print(type(tupledata))

<class 'list'>
<class 'tuple'>


In [9]:
listarray = np.asarray(listdata)
tuplearray = np.asarray(tupledata)

In [11]:
print(listarray)
print(tuplearray)
print(type(listarray))
print(type(tuplearray))

[1 2 3 4 5 6]
[[8 4 6]
 [1 2 3]]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
