In [1]:
# To mulitply all elements of array by 3 and print it

In [2]:
import numpy as np

In [14]:
data = np.arange(12).reshape(3,4)
print(data)
for i in np.nditer(data,op_flags=['readwrite']):
    i[...] = i * 3
print(data)    

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]
