In [1]:
import numpy as np

In [2]:
array = np.zeros([5,5])
print(array)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [3]:
print(array[1:4,1:4])
array[1:4,1:4] = 1

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [4]:
print(array)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]
