In [1]:
import numpy as np

In [11]:
array = np.ones([5,5])
print(array)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [34]:
print(array[1:4,1:4])
array[1:4,1:4] = 0

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [35]:
print(array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
