In [1]:
#To save the numpy array to file

In [2]:
import numpy as np

In [6]:
data = np.arange(1,10).reshape(3,3)
print(data)
np.savetxt('Test.txt',data,header='file data')
result = np.loadtxt('Test.txt')
print(result)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
